//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTPC_SAFETY.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SafetyForm
    {
        public string ProjCode { get; set; }

        [DataType(DataType.Date)]
        public System.DateTime Date { get; set; }
        public string SafetyTip { get; set; }
        public int TrainingsToTrainers { get; set; }
        public int ID { get; set; }
        public string RiskGovernance { get; set; }
        public Nullable<int> TrainingToContractor { get; set; }
        public Nullable<int> TrainingToNTPCEng { get; set; }
        public Nullable<int> TrainingToHods { get; set; }
        public string SafetyPolicyDisplay { get; set; }
        public string StartOfMeetingsWithSafety { get; set; }
        public string DistributionOfPPES { get; set; }
        public string EntryWithPPES { get; set; }
        public string SafetyControlRoomFunc { get; set; }
        public string ScreeningOfSafetyFilms { get; set; }
        public string OverHaulsUnderDUPONT { get; set; }
        public string SafetyContractsMgmt { get; set; }
        public string RevisedSafetyProvisions { get; set; }
        public string SafetyProcessMgmt { get; set; }
        public Nullable<int> InternalAudits { get; set; }
        public string IntenalAuditsActionTaken { get; set; }
        public string InternalAuditSchedule { get; set; }
        public Nullable<int> ExternalAudits { get; set; }
        public string ExternalAuditsActionTaken { get; set; }
        public string ExternalAuditSchedule { get; set; }
        public string Compliance { get; set; }
        public string InternalMOU { get; set; }
        public string ArticleOfTheMonth { get; set; }
        public string SafetyInBusinessModel { get; set; }
        public string ReplaceOldConcreteSlabs { get; set; }
        public string ProtectionOfStructures { get; set; }
        public string DividingPlantIntoAreas { get; set; }
        public string CheckListForEngineers { get; set; }
        public string MockDrillsStatus { get; set; }
        public string FactoryOccupierDeclarationStatus { get; set; }
        public string ATROnDirectors { get; set; }
        public bool Lock { get; set; }
    
        public virtual Project Project { get; set; }
    }
}
